define(function() {

	var Data = function() {};

	var data = {
	"ANIMATEDARROW.PNG": "assets/images/AnimatedArrow.png",
	"ARROWBULLET.PNG": "assets/images/ArrowBullet.png",
	"BALL.PNG": "assets/images/Ball.png",
	"BLOB.PNG": "assets/images/Blob.png",
	"BOSS1BODY.PNG": "assets/images/Boss1/Boss1Body.png",
	"BOSS1CABLE.PNG": "assets/images/Boss1/Boss1Cable.png",
	"BOSS1CABLEDAMAGED.PNG": "assets/images/Boss1/Boss1CableDamaged.png",
	"BOSS2BODY.PNG": "assets/images/Boss2/Boss2Body.png",
	"BOSS2CORE.PNG": "assets/images/Boss2/Boss2Core.png",
	"BOSS3INNEREYE.PNG": "assets/images/Boss3/Boss3InnerEye.png",
	"BOSS3OUTEREYE.PNG": "assets/images/Boss3/Boss3OuterEye.png",
	"GENERATORWAYPOINT.PNG": "assets/images/Boss3/GeneratorWayPoint.png",
	"BOSS4BODY.PNG": "assets/images/Boss4/Boss4Body.png",
	"BOSSCANNONBASE.PNG": "assets/images/BossCannon/BossCannonBase.png",
	"BOSSCANNONSHOOTER.PNG": "assets/images/BossCannon/BossCannonShooter.png",
	"BOSSGENERATOR.PNG": "assets/images/BossGenerator.png",
	"BOSSLASERTURRET.PNG": "assets/images/BossLaserTurret.png",
	"BOSS1PORTRAIT.PNG": "assets/images/BossPortraits/Boss1Portrait.png",
	"BOSS2PORTRAIT.PNG": "assets/images/BossPortraits/Boss2Portrait.png",
	"BOSS3PORTRAIT.PNG": "assets/images/BossPortraits/Boss3Portrait.png",
	"BOSS4PORTRAIT.PNG": "assets/images/BossPortraits/Boss4Portrait.png",
	"BURST.PNG": "assets/images/Burst.png",
	"CANNONBASE.PNG": "assets/images/Cannon/CannonBase.png",
	"CANNONSHOOTER.PNG": "assets/images/Cannon/CannonShooter.png",
	"CHECKEREDFLAG.PNG": "assets/images/CheckeredFlag.png",
	"CHECKEREDFLAGDOWN.PNG": "assets/images/CheckeredFlagDown.png",
	"CHECKEREDFLAGLEFT.PNG": "assets/images/CheckeredFlagLeft.png",
	"CHECKEREDFLAGRIGHT.PNG": "assets/images/CheckeredFlagRight.png",
	"CHECKEREDFLAGUP.PNG": "assets/images/CheckeredFlagUp.png",
	"DOUBLECANNON.PNG": "assets/images/DoubleCannon.png",
	"ENEMYSHIP1.PNG": "assets/images/EnemyShip1.png",
	"ENEMYSHIP2.PNG": "assets/images/EnemyShip2.png",
	"FASTDOWNARROW.PNG": "assets/images/FastDownArrow.png",
	"FASTLEFTARROW.PNG": "assets/images/FastLeftArrow.png",
	"FASTRIGHTARROW.PNG": "assets/images/FastRightArrow.png",
	"FASTUPARROW.PNG": "assets/images/FastUpArrow.png",
	"FLAG.PNG": "assets/images/Flag.png",
	"GENERATOR.PNG": "assets/images/Generator.png",
	"HPMETER.PNG": "assets/images/HPMeter.png",
	"HEALTHUP.PNG": "assets/images/HealthUp.png",
	"LASERBASE.PNG": "assets/images/LaserBase.png",
	"LASERHIT.PNG": "assets/images/LaserHit.png",
	"LASERTURRET.PNG": "assets/images/LaserTurret.png",
	"LEVELCOMPLETEICON.PNG": "assets/images/LevelCompleteIcon.png",
	"LEVELFRAME.PNG": "assets/images/LevelFrame.png",
	"MINE.PNG": "assets/images/Mine.png",
	"MINIBLOB.PNG": "assets/images/MiniBlob.png",
	"BOSSMISSILETURRETSHOOTER.PNG": "assets/images/MissileTurret/BossMissileTurretShooter.png",
	"MISSILE.PNG": "assets/images/MissileTurret/Missile.png",
	"MISSILETURRETBASE.PNG": "assets/images/MissileTurret/MissileTurretBase.png",
	"MISSILETURRETHINGE.PNG": "assets/images/MissileTurret/MissileTurretHinge.png",
	"MISSILETURRETSHOOTER.PNG": "assets/images/MissileTurret/MissileTurretShooter.png",
	"MOON.PNG": "assets/images/Moon.png",
	"PLAYERBULLET1.PNG": "assets/images/PlayerBullet1.png",
	"PLAYEREXHAUST.PNG": "assets/images/PlayerExhaust.png",
	"POWERUP.PNG": "assets/images/PowerUp.png",
	"ROUNDBULLET.PNG": "assets/images/RoundBullet.png",
	"SMALLSPIDER.PNG": "assets/images/SmallSpider.png",
	"SOUND.PNG": "assets/images/Sound.png",
	"SPEEDUP.PNG": "assets/images/SpeedUp.png",
	"STAR.PNG": "assets/images/Star.png",
	"STOP.PNG": "assets/images/Stop.png",
	"WARNING.PNG": "assets/images/Warning.png",
	"BIOHAZARD.PNG": "assets/images/biohazard.png",
	"DOWNARROW.PNG": "assets/images/downArrow.png",
	"DOWNLEFTARROW.PNG": "assets/images/downLeftArrow.png",
	"DOWNRIGHTARROW.PNG": "assets/images/downRightArrow.png",
	"LEFTARROW.PNG": "assets/images/leftArrow.png",
	"RIGHTARROW.PNG": "assets/images/rightArrow.png",
	"UPARROW.PNG": "assets/images/upArrow.png",
	"UPLEFTARROW.PNG": "assets/images/upLeftArrow.png",
	"UPRIGHTARROW.PNG": "assets/images/upRightArrow.png",
	"WEBBULLET.PNG": "assets/images/webBullet.png",
	"BACK.OGG": "assets/sound/back.ogg",
	"BLOOB.OGG": "assets/sound/bloob.ogg",
	"BUG.OGG": "assets/sound/bug.ogg",
	"DEFLECT.OGG": "assets/sound/deflect.ogg",
	"EXPLOSION1.OGG": "assets/sound/explosion1.ogg",
	"EXPLOSION2.OGG": "assets/sound/explosion2.ogg",
	"EXPLOSION3.OGG": "assets/sound/explosion3.ogg",
	"EXPLOSION4.OGG": "assets/sound/explosion4.ogg",
	"EXPLOSION5.OGG": "assets/sound/explosion5.ogg",
	"EXPLOSION6.OGG": "assets/sound/explosion6.ogg",
	"EXPLOSION7.OGG": "assets/sound/explosion7.ogg",
	"HIT.OGG": "assets/sound/hit.ogg",
	"INTRO.OGG": "assets/sound/intro.ogg",
	"LARGEBUG.OGG": "assets/sound/largeBug.ogg",
	"LEVEL1.OGG": "assets/sound/level1.ogg",
	"OK.OGG": "assets/sound/ok.ogg",
	"OPENHATCH.OGG": "assets/sound/openHatch.ogg",
	"PLAYERDAMAGE.OGG": "assets/sound/playerDamage.ogg",
	"PLAYERSHOT.OGG": "assets/sound/playerShot.ogg",
	"POWERUP.OGG": "assets/sound/powerUp.ogg",
	"SELECT.OGG": "assets/sound/select.ogg",
	"SMALLLAUNCH.OGG": "assets/sound/smallLaunch.ogg"
};

	Data.prototype.get = function() {
		return data;
	}

	return new Data();
});